FROM n8nio/n8n

# Environment variables
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=MyStrongPassword123

# Expose port
EXPOSE 5678

# Start n8n
CMD ["n8n"]